apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/apps/kanboard

helmCharts:
- name: kanboard
  namespace: kanboard
  version: 1.0.2
  repo: https://kube-the-home.github.io/kanboard-helm
  valuesFile: ../../../../base/apps/kanboard/values.yaml
  releaseName: ""
  valuesInline:
     fullnameOverride: kanboard
  includeCRDs: true
