apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: cert-manager
resources:
  - namespace.yaml
  - clusterissuer.yaml

# --------------------------------------------
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# components:
# - ../../../../base/infra/cert-manager

# helmCharts:
# - name: cert-manager
#   version: 1.16.1
#   repo: https://charts.jetstack.io
#   valuesFile: ../../../../base/infra/cert-manager/values.yaml
#   releaseName: ""
#   valuesInline:
#      fullnameOverride: cert-manager
#   includeCRDs: true

