apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- ../../../../base/infra/cert-manager/

resources:
- ../../../../base/infra/cert-manager/resources

patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
      name: letsencrypt-prod
    path: clusterissuer-patch.yaml
