apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/apps/forgejo

helmCharts:
- name: forgejo
  namespace: forgejo
  version: 14.0.1
  repo: oci://code.forgejo.org/forgejo-helm/forgejo
  valuesFile: ../../../../base/apps/forgejo/values.yaml
  releaseName: ""
  valuesInline:
     fullnameOverride: forgejo
  includeCRDs: true
