ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: contour
    hosts:
      - host: papers.rabarbra.me
        paths:
          - path: /
    tls:
      - secretName: paperless-ngx-tls
        hosts:
          - papers.rabarbra.me
persistence:
  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 4Gi
config:
  redis:
    url: "redis://release-name-redis-master:6379"
env:
  PAPERLESS_REDIS: "redis://release-name-redis-master:6379"
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  global:
    storageClass: "nfs-client"
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false
