ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: contour
    hosts:
      - host: papers.rabarbra.me
        paths:
          - path: /
    tls:
      - secretName: paperless-ngx-tls
        hosts:
          - papers.rabarbra.me
