apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/infra/projectcontour

helmCharts:
- name: contour
  namespace: projectcontour
  version: 19.5.11
  repo: https://charts.bitnami.com/bitnami/
  valuesFile: ../../../../base/infra/projectcontour/values.yaml
  valuesInline:
     fullnameOverride: contour
  includeCRDs: true