longhornUI:
  replicas: 1
longhornAdmissionWebhook:
  replicas: 1
longhornRecoveryBackend:
  replicas: 1
ingress:
  enabled: true
  ingressClassName: contour
  host: lh.rabarbra.me
  tls: true
  secureBackends: false
  tlsSecret: longhorn-tls
  path: /
  annotations:
    kubernetes.io/tls-acme: true
    cert-manager.io/cluster-issuer: letsencrypt-prod
