apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: nfs
resources:
  - namespace.yaml

# --------------------------------------------
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# components:
# - ../../../../base/infra/nfs-server

# helmCharts:
# - name: nfs-server-provisioner
#   namespace: nfs
#   version: 1.8.0
#   repo: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
#   valuesFile: ../../../../base/infra/nfs-server/values.yaml
#   valuesInline:
#      fullnameOverride: nfs-server-provisioner
#   includeCRDs: true
