persistence:
  enabled: true
  storageClass: "local-path"
  size: 150Gi
storageClass:
  name: nfs-client
  defaultClass: true
  mountOptions:
    - soft
    - retrans=2
    - timeo=30
nodeSelector:
  node-role.kubernetes.io/master: "true"