application:
  port: 80
  additionalLabels: {}
  persistence:
    enabled: true
    persistentVolumeClaim:
      name: kanboard-pvc
      create: true
      storageClass: "nfs-client"
      size: 10Mi
      accessMode: ReadWriteMany

nodePort:
  enabled: false
  port: ~

clusterip:
  enabled: false
  port: 8080

ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
  host: kanboard.rabarbra.me
  tls:
    - secretName: kanboard-tls
      hosts:
        - kanboard.rabarbra.me
