apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Apps
  sourceRepos:
  - '*'
  destinations:
  - '*'
  clusterResourceWhitelist:
  - '*'
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist:
  - '*'
