apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/apps/web-tty

helmCharts:
- name: web-tty
  namespace: web-tty
  version: 0.1.0
  repo: https://rabarbra.github.io/charts/
  valuesFile: ../../../../base/apps/web-tty/values.yaml
  releaseName: ""
  valuesInline:
     fullnameOverride: web-tty
  includeCRDs: true
