ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: home.rabarbra.me
      paths:
        - path: /
  tls:
    - secretName: homarr-tls
      hosts:
        - home.rabarbra.me
persistence:
  homarrDatabase:
    enabled: true
    storageClassName: "nfs-client"
    size: "1Gi"
