ingress:
  enabled: true
  ingressClassName: "contour"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: contour
  hosts:
    - host: home.rabarbra.me
      paths:
        - path: /
  tls:
    - secretName: homarr-tls
      hosts:
        - home.rabarbra.me
persistence:
  homarrDatabase:
    enabled: true
    storageClassName: "nfs-client"
    size: "1Gi"
