apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: authentik
resources:
  - namespace.yaml

# --------------------------------------------
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# components:
# - ../../../../base/infra/authentik

# helmCharts:
# - name: authentik
#   namespace: authentik
#   version: 2025.6.4
#   repo: https://charts.goauthentik.io
#   valuesFile: ../../../../base/infra/authentik/values.yaml
#   releaseName: ""
#   valuesInline:
#      fullnameOverride: authentik
#   includeCRDs: true
