ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.rabarbra.me`)
    entryPoints:
      - web
providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
