ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.rabarbra.me`)
    entryPoints: [websecure]
    middlewares:
      - name: authentik
        namespace: authentik
    tls:
      secretName: traefik-dashboard-tls
providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
ports:
  forgejo-ssh:
    port: 2222
    expose:
      default: true
    exposedPort: 2222
    protocol: TCP
