ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.rabarbra.me`)
    entryPoints:
      - web
    middlewares:
      - name: authentik
        namespace: authentik
providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
