- Platform:
  - Authentik:
      href: https://authentik.rabarbra.me
      icon: authentik.png
      widgets:
        - type: authentik
          url: https://authentik.rabarbra.me
          key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
          version: "2025.6.4"
  - Forgejo:
      href: https://git.rabarbra.me
      icon: gitea.png
      widgets:
        - type: gitea
          url: https://git.rabarbra.me
          key: "{{HOMEPAGE_VAR_GITEA_TOKEN}}"
          fields: ["notifications","issues","pulls"]
  - Changedetection.io:
      href: https://change.rabarbra.me
      widgets:
        - type: changedetectionio
          url: https://change.rabarbra.me
          key: "{{HOMEPAGE_VAR_CHANGEDETECTION_KEY}}"
          fields: ["diffsDetected","totalObserved"]
  - Filebrowser:
      href: https://files.rabarbra.me
      icon: filebrowser.png
      widgets:
        - type: filebrowser
          url: https://files.rabarbra.me
          username: "{{HOMEPAGE_VAR_FILEBROWSER_USER}}"
          password: "{{HOMEPAGE_VAR_FILEBROWSER_PASS}}"
  - Paperless-ngx:
      href: https://papers.rabarbra.me
      icon: paperless-ngx.png
      widgets:
        - type: paperlessngx
          url: https://papers.rabarbra.me
          key: "{{HOMEPAGE_VAR_PAPERLESS_TOKEN}}"
          fields: ["total","inbox"]
  - Vikunja:
      href: https://tasks.rabarbra.me
      icon: vikunja.png
      widgets:
        - type: vikunja
          url: https://tasks.rabarbra.me
          key: "{{HOMEPAGE_VAR_VIKUNJA_KEY}}"
          enableTaskList: true
          fields: ["projects","tasks7d","tasksOverdue","tasksInProgress"]
