apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/apps/paperless-ngx

helmCharts:
- name: paperless
  namespace: paperless-ngx
  version: 9.86.0
  repo: https://zekker6.github.io/helm-charts/
  valuesFile: ../../../../base/apps/paperless-ngx/values.yaml
  releaseName: ""
  valuesInline:
     fullnameOverride: paperless-ngx
  includeCRDs: true
