ntfy:
  baseURL: "https://ntfy.rabarbra.me"
  cache:
    file: /data/cache.db
  attachment:
    cacheDir: /data
ingress:
  enabled: true
  className: contour
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    projectcontour.io/websocket-routes: "/"
  hosts:
    - host: ntfy.rabarbra.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: ntfy-tls
     hosts:
       - ntfy.rabarbra.me
persistence:
  enabled: true