apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: uptime-kuma
resources:
  - helmchart.yaml

patches:
  - target:
      kind: HelmChartInflationGenerator
      name: base
    patch: |-
      [
        {
          "op": "add",
          "path": "/additionalValuesFiles",
          "value": ["values.yaml"]
        }
      ]
