nodeSelector:
  node-role.kubernetes.io/master: "true"
ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: uptime.rabarbra.me
      paths:
        - path: "/"
          pathType: ImplementationSpecific
  tls:
    - secretName: uptime-kuma-tls
      hosts:
        - uptime.rabarbra.me
volume:
  accessMode: ReadWriteMany
