image:
  pullPolicy: Always
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: sh.rabarbra.me
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: web-tty-tls
    hosts:
      - sh.rabarbra.me
