apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: forgejo
resources:
  - namespace.yaml
  - ssh-route.yaml
  # - themes.yaml

secretGenerator:
  - name: forgejo-themes
    namespace: forgejo
    files:
      - themes/theme-aquamarine.css
      - themes/theme-dark.css
      - themes/theme-dracula.css
      - themes/theme-edge-auto.css
      - themes/theme-everforest-auto.css
      - themes/theme-gruvbox-auto.css
      - themes/theme-gruvbox-material-auto.css
      - themes/theme-hotline.css
      - themes/theme-hotpink.css
      - themes/theme-maroon.css
      - themes/theme-nord-sainnhe.css
      - themes/theme-nord.css
      - themes/theme-organizr.css
      - themes/theme-overseerr.css
      - themes/theme-palenight.css
      - themes/theme-plex.css
      - themes/theme-soft-era.css
      - themes/theme-sonokai.css
      - themes/theme-sonokai-andromeda.css
      - themes/theme-space-gray.css
    options:
      disableNameSuffixHash: true

# --------------------------------------------
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# components:
# - ../../../../base/apps/forgejo

# helmCharts:
# - name: forgejo
#   namespace: forgejo
#   version: 14.0.1
#   repo: oci://code.forgejo.org/forgejo-helm/forgejo
#   valuesFile: ../../../../base/apps/forgejo/values.yaml
#   releaseName: ""
#   valuesInline:
#      fullnameOverride: forgejo
#   includeCRDs: true
