apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../base/infra/contour

helmCharts:
- name: contour
  namespace: projectcontour
  version: 19.3.1
  repo: https://charts.bitnami.com/bitnami
  valuesFile: ../../../../base/infra/contour/values.yaml
  valuesInline:
     fullnameOverride: contour
  includeCRDs: true
