ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: files.rabarbra.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: filebrowser-tls
    hosts:
      - files.rabarbra.me
rootDir:
  type: pvc
  readOnly: false
  hostPath:
    path: /
  pvc:
    storageClassName: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 2Gi
db:
  pvc:
    enabled: true
    storageClassName: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 256Ki
config:
  port: 8080
  baseURL: ""
  address: ""
  log: stdout
  database: /db/database.db
  root: /rootdir
