server:
  standalone:
    enabled: true
    config: |
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
  service:
    enabled: true
  dataStorage:
    enabled: true
    size: 2Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: contour
    pathType: Prefix
    activeService: true
    hosts:
      - host: vault.rabarbra.me
        paths:
          - /
    tls:
      - secretName: vault-tls
        hosts:
          - vault.rabarbra.me
ui:
  enabled: true
  serviceType: ClusterIP