ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: h.rabarbra.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: homepage-tls
      hosts:
        - h.rabarbra.me

config:
  allowedHosts:
    - h.rabarbra.me
extraEnvFrom:
  - secretRef:
      name: homepage-secrets

volumes:
  - name: homepage-config
    configMap:
      name: homepage-config

volumeMounts:
  - name: homepage-config
    mountPath: /app/config/kubernetes.yaml
    subPath: kubernetes.yaml
  - name: homepage-config
    mountPath: /app/config/settings.yaml
    subPath: settings.yaml
  - name: homepage-config
    mountPath: /app/config/services.yaml
    subPath: services.yaml
  - name: homepage-config
    mountPath: /app/config/widgets.yaml
    subPath: widgets.yaml
  - name: homepage-config
    mountPath: /app/config/bookmarks.yaml
    subPath: bookmarks.yaml
