ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: h.rabarbra.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: homepage-tls
      hosts:
        - h.rabarbra.me
