apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/rabarbra/argo-gitops-monorepo/
      revision: HEAD
      directories:
        - path: 'clusters/*/*/*'
        - path: 'clusters/*/*/disabled'
          exclude: true
      values:
        clusterName: '{{index .path.segments 1}}'
        projectName: '{{index .path.segments 2}}'
        appName: '{{index .path.segments 3}}'
  template:
    metadata:
      name: '{{ .values.clusterName }}-{{ .values.appName }}'
    spec:
      project: '{{ .values.projectName }}'
      source:
        repoURL: https://github.com/rabarbra/argo-gitops-monorepo/
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        name: '{{ .values.clusterName }}'
        namespace: '{{ .values.appName }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle