apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        mergeKeys:
          - values.clusterName
        generators:
          - clusters:
              values:
                clusterName: '{{ .name | default "unknown-cluster" }}'
          - git:
              repoURL: https://github.com/rabarbra/argo-gitops-monorepo/
              revision: HEAD
              directories:
                - path: 'clusters/*/*/*'
              values:
                clusterName: '{{index .path.segments 1 | default "unknown-cluster"}}'
                projectName: '{{index .path.segments 2}}'
                appName: '{{index .path.segments 3}}'
  template:
    metadata:
      name: '{{ .values.appName }}'
    spec:
      project: '{{ .values.projectName }}'
      source:
        repoURL: https://github.com/rabarbra/argo-gitops-monorepo/
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: '{{ .values.clusterName }}'
        namespace: '{{ .values.appName }}'
